# DevEnvUbuntu v2: WSL keepalive setup
# 注册任务计划: 一个任务,两个 trigger (AtLogOn + 每 5 分钟),
# 跑同一个 wsl-heartbeat.vbs (智能心跳: active->记日志, 否则触发 boot)
[CmdletBinding()]
param(
  [string]$Distro,        # 不指定则自动检测默认 distro
  [string]$WslUser        # 不指定则在 distro 里 whoami
)

$ErrorActionPreference = "Stop"

# 校验管理员
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
  Write-Error "请用管理员权限运行(双击 run-as-admin.bat)"
  exit 1
}

# wsl.exe 输出 UTF-8
$env:WSL_UTF8 = "1"
$prevConsoleOut = [Console]::OutputEncoding
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

try {

  # === 1) 写 .wslconfig =====================================================
  $repoRoot = Split-Path -Parent $PSCommandPath
  $src = Join-Path $repoRoot "wslconfig.template"
  $dst = Join-Path $env:USERPROFILE ".wslconfig"
  Copy-Item $src $dst -Force
  Write-Host "[OK] 已写入 $dst"

  # === 2) 自动检测 WSL distro ==============================================
  if (-not $Distro) {
    $rawList = & wsl.exe -l -q 2>&1
    $candidates = @()
    foreach ($line in $rawList) {
      $clean = ($line.ToString() -replace "`0", "").Trim()
      if ($clean -match '^[A-Za-z][A-Za-z0-9._-]*$') { $candidates += $clean }
    }
    if (-not $candidates) {
      Write-Host "[ERROR] wsl -l -q 没列出任何 distro,原始输出:" -ForegroundColor Red
      $rawList | ForEach-Object { Write-Host "  > $_" }
      Write-Error "找不到 WSL distro。先安装一个: wsl --install -d Ubuntu"
      exit 1
    }
    $Distro = $candidates | Where-Object { $_ -match '^Ubuntu' } | Select-Object -First 1
    if (-not $Distro) { $Distro = $candidates | Select-Object -First 1 }
    Write-Host "[INFO] 检测到 distro 候选: $($candidates -join ', '); 使用: $Distro"
  } else {
    Write-Host "[INFO] 使用指定 distro: $Distro"
  }

  # === 3) 自动检测 WSL user ================================================
  if (-not $WslUser) {
    $rawUser = & wsl.exe -d $Distro -e whoami 2>&1
    $WslUser = ($rawUser | Out-String).Trim()
  }
  if (-not ($WslUser -match '^[a-z_][a-z0-9_-]*\$?$')) {
    Write-Host "[ERROR] 拿到的 WSL user 不合法: '$WslUser'" -ForegroundColor Red
    Write-Host "         如果上面是中文乱码,说明 wsl.exe 输出了错误信息" -ForegroundColor Red
    Write-Host "         检查: wsl -l -v   或手动 -Distro <name> -WslUser <user>" -ForegroundColor Red
    Write-Error "无法解析 WSL 用户名"
    exit 1
  }
  Write-Host "[INFO] 目标 distro=$Distro user=$WslUser"

  # === 4) 清理 v1 残留 ======================================================
  # 4a) 杀 v1 sleep-infinity 长跑进程
  $existingProcs = Get-CimInstance Win32_Process -Filter "Name = 'wsl.exe'" -ErrorAction SilentlyContinue
  foreach ($ep in $existingProcs) {
    if ($ep.CommandLine -and ($ep.CommandLine -match 'exec sleep infinity')) {
      Write-Host "[INFO] 终止 v1 残留保活进程 PID=$($ep.ProcessId)"
      Stop-Process -Id $ep.ProcessId -Force -ErrorAction SilentlyContinue
    }
  }
  # 4b) 删 v1 旧 VBS
  $launcherDir = Join-Path $env:LOCALAPPDATA "DevEnvUbuntu"
  if (-not (Test-Path $launcherDir)) {
    New-Item -ItemType Directory -Path $launcherDir -Force | Out-Null
  }
  $oldVbs = Join-Path $launcherDir "wsl-keepalive.vbs"
  if (Test-Path $oldVbs) {
    Remove-Item $oldVbs -Force
    Write-Host "[INFO] 删除 v1 VBS: $oldVbs"
  }

  # === 5) 生成 wsl-heartbeat.vbs ==========================================
  $vbsPath  = Join-Path $launcherDir "wsl-heartbeat.vbs"
  $logPath  = Join-Path $launcherDir "heartbeat.log"
  $signature = "DevEnvUbuntu-keepalive:${Distro}:${WslUser}"

  # PowerShell 字符串里 ` 是 escape, " 用 "" 转义; 用 here-string 简化
  $vbs = @"
' DevEnvUbuntu v2 wsl-heartbeat.vbs
' Auto-generated by setup-keepalive.ps1 - do not edit by hand
Option Explicit

Const DISTRO    = "$Distro"
Const WSL_USER  = "$WslUser"
Const SIGNATURE = "$signature"
Const LOG_PATH  = "$($logPath -replace '\\','\\')"
Const MAX_LOG_BYTES = 1048576    ' 1 MB rotate threshold

' --- helper: 追加一行带时间戳的日志 -----------------------------------------
Sub LogLine(level, msg)
  Dim fso, f
  Set fso = CreateObject("Scripting.FileSystemObject")
  ' rotate if too big
  If fso.FileExists(LOG_PATH) Then
    If fso.GetFile(LOG_PATH).Size > MAX_LOG_BYTES Then
      Dim rotated : rotated = LOG_PATH & ".1"
      If fso.FileExists(rotated) Then fso.DeleteFile rotated, True
      fso.MoveFile LOG_PATH, rotated
    End If
  End If
  Set f = fso.OpenTextFile(LOG_PATH, 8, True)   ' 8=ForAppending
  Dim ts : ts = FormatDateTime(Now, 0)
  f.WriteLine ts & " [" & level & "] " & msg
  f.Close
End Sub

' --- (a) wscript 排他兜底 (任务计划 MultipleInstances=IgnoreNew 是主防护) ---
Dim wmi, procs, p, dupCount, myPid
myPid = -1
On Error Resume Next
Set wmi = GetObject("winmgmts:\\.\root\cimv2")
Set procs = wmi.ExecQuery( _
  "SELECT ProcessId, CommandLine FROM Win32_Process WHERE Name = 'wscript.exe'")
dupCount = 0
For Each p In procs
  If Not IsNull(p.CommandLine) Then
    If InStr(p.CommandLine, "wsl-heartbeat.vbs") > 0 Then
      dupCount = dupCount + 1
    End If
  End If
Next
On Error GoTo 0
If dupCount > 1 Then
  ' 已有别的 heartbeat 在跑,我退出 (任何一份都行)
  WScript.Quit 0
End If

' --- (b) 探活: 隐藏窗口运行 wsl.exe 并把 stdout 重定向到临时文件 ----------
' WshShell.Exec 强制 SW_SHOWNORMAL,会闪黑窗;改用 Run(cmd, 0, True),
' 0=vbHide,True=同步等待,返回 wsl.exe 的 exit code.
Dim sh : Set sh = CreateObject("WScript.Shell")
Dim tempFile, coreCmd, probeCmd, exitCode, statusOutput
tempFile = sh.ExpandEnvironmentStrings("%LOCALAPPDATA%") & _
           "\DevEnvUbuntu\probe.tmp"
coreCmd  = "wsl.exe -d " & DISTRO & " -u " & WSL_USER & _
           " -e systemctl --user is-active clautel.service"
' cmd.exe /c "..." 双双引号包整串,内层引号保护 tempFile 路径里可能的空格
probeCmd = "cmd.exe /c """ & coreCmd & " > """ & tempFile & """ 2>&1"""
exitCode = sh.Run(probeCmd, 0, True)

' 读临时文件 (不存在时 statusOutput 留空,自然落 WARN 分支触发 boot)
Dim fso, f2
Set fso = CreateObject("Scripting.FileSystemObject")
statusOutput = ""
If fso.FileExists(tempFile) Then
  Set f2 = fso.OpenTextFile(tempFile, 1)   ' 1=ForReading
  If Not f2.AtEndOfStream Then statusOutput = f2.ReadAll()
  f2.Close
  fso.DeleteFile tempFile, True
End If
' VBS 的 Trim() 不剥换行;systemctl 输出是 "active\n",必须先去 CR/LF
statusOutput = Replace(statusOutput, vbCrLf, "")
statusOutput = Replace(statusOutput, vbLf,   "")
statusOutput = Replace(statusOutput, vbCr,   "")
statusOutput = Trim(statusOutput)

' --- (c) 三态分流 ----------------------------------------------------------
If exitCode = 0 And statusOutput = "active" Then
  LogLine "OK", "clautel.service active"
ElseIf statusOutput = "activating" Then
  LogLine "INFO", "clautel.service activating, give it time"
Else
  LogLine "WARN", "clautel down (status='" & statusOutput & "', exit=" & exitCode & "), bootstrapping"

  Dim bootCmd
  bootCmd = "wsl.exe -d " & DISTRO & " -u " & WSL_USER & _
            " --exec /bin/bash -lic ""systemctl --user start clautel.service; exit 0  # " & SIGNATURE & """"

  ' 隐藏窗口启动,不等待
  sh.Run bootCmd, 0, False
  LogLine "INFO", "boot trigger fired"
End If
"@

  # 写文件 (ASCII 即可,不需要 BOM,wscript 都吃)
  $vbs | Set-Content -Path $vbsPath -Encoding Ascii -Force
  Write-Host "[OK] 已生成: $vbsPath"

  # === 6) 注册任务: 一个任务,两个 trigger ==================================
  $taskName = "DevEnvUbuntu-WSL-Keepalive"
  $wscript  = Join-Path $env:SystemRoot "System32\wscript.exe"

  $action = New-ScheduledTaskAction -Execute $wscript `
    -Argument ('"{0}"' -f $vbsPath)

  $triggerStartup = New-ScheduledTaskTrigger -AtStartup

  # 5 分钟一次心跳: 开机 2 分钟后第一次,然后每 5 分钟 (PowerShell 里 -Once -At + RepetitionInterval 是唯一支持周期触发的写法)
  $triggerHeartbeat = New-ScheduledTaskTrigger `
    -Once -At ((Get-Date).AddMinutes(2)) `
    -RepetitionInterval (New-TimeSpan -Minutes 5)

  $settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -ExecutionTimeLimit ([TimeSpan]::Zero) -Hidden `
    -MultipleInstances IgnoreNew

  $principal = New-ScheduledTaskPrincipal `
    -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType S4U -RunLevel Highest

  Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue
  Register-ScheduledTask -TaskName $taskName `
    -Action $action `
    -Trigger @($triggerStartup, $triggerHeartbeat) `
    -Settings $settings -Principal $principal | Out-Null
  Write-Host "[OK] 已注册任务计划: $taskName (AtStartup + 5min, S4U, MultipleInstances=IgnoreNew)"

  # === 6b) 自检注册结果 (防止后续被人意外改回 AtLogOn 或丢掉 S4U) ============
  $registered = Get-ScheduledTask -TaskName $taskName
  $bootTrigger = $registered.Triggers | Where-Object {
    $_.CimClass.CimClassName -eq 'MSFT_TaskBootTrigger'
  }
  if (-not $bootTrigger) {
    throw "[ASSERT] 任务注册成功了, 但没找到 AtStartup (MSFT_TaskBootTrigger). 检查 setup-keepalive.ps1 中 trigger 写法."
  }
  if ($registered.Principal.LogonType -ne 'S4U') {
    throw "[ASSERT] 任务 principal LogonType = '$($registered.Principal.LogonType)', 期望 S4U. 检查 New-ScheduledTaskPrincipal 参数."
  }
  Write-Host "[OK] 配置断言通过: AtStartup trigger + S4U principal"

  # === 7) 立即触发一次 + 写 WSL 标记 =======================================
  Start-ScheduledTask -TaskName $taskName
  Start-Sleep -Seconds 5
  & wsl.exe -d $Distro -u $WslUser -e bash -c "mkdir -p ~/.local/state/devenv && touch ~/.local/state/devenv/windows-keepalive-installed"
  Write-Host "[OK] WSL 端已写入标记文件"

  # === 8) 自检 =============================================================
  if (Test-Path $logPath) {
    $lastLine = Get-Content $logPath -Tail 1 -ErrorAction SilentlyContinue
    Write-Host "[OK] heartbeat.log 末行: $lastLine"
  } else {
    Write-Host "[WARN] heartbeat.log 还没生成,几分钟后查 $logPath" -ForegroundColor Yellow
  }

  Write-Host ""
  Write-Host "=== 完成 ===" -ForegroundColor Green
  Write-Host "保活机制:"
  Write-Host "  AtStartup (S4U, 无密码) + 每 5 分钟 -> wscript $vbsPath"
  Write-Host "  VBS 探活 clautel.service: active=记 OK / 否则 systemctl start"
  Write-Host "  日志: $logPath"
  Write-Host ""
  Write-Host "卸载: Unregister-ScheduledTask -TaskName $taskName -Confirm:`$false"
  Write-Host "      Remove-Item '$launcherDir' -Recurse"

} finally {
  [Console]::OutputEncoding = $prevConsoleOut
}
