# DevEnvUbuntu v3: WSL VM Holder setup
# 注册任务计划 DevEnvUbuntu-WSL-VMHolder: 单 trigger AtStartup, S4U principal,
# RestartCount=999 / Interval=60s. 任务跑 wscript.exe vm-holder.vbs (运行时生成),
# VBS 持有 wsl.exe sleep infinity 子进程让 VM 24/7 在线, 每 5min 探活 clautel.service.
# 见 docs/superpowers/specs/2026-05-11-vm-holder-design.md.
[CmdletBinding()]
param(
  [string]$Distro,        # 不指定则自动检测默认 distro
  [string]$WslUser        # 不指定则在 distro 里 whoami
)

$ErrorActionPreference = "Stop"

# 校验管理员
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
  Write-Error "请用管理员权限运行(双击 run-as-admin.bat)"
  exit 1
}

# wsl.exe 输出 UTF-8
$env:WSL_UTF8 = "1"
$prevConsoleOut = [Console]::OutputEncoding
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

try {

  # === 1) 写 .wslconfig =====================================================
  $repoRoot = Split-Path -Parent $PSCommandPath
  $src = Join-Path $repoRoot "wslconfig.template"
  $dst = Join-Path $env:USERPROFILE ".wslconfig"
  Copy-Item $src $dst -Force
  Write-Host "[OK] 已写入 $dst"

  # === 2) 自动检测 WSL distro ==============================================
  if (-not $Distro) {
    $rawList = & wsl.exe -l -q 2>&1
    $candidates = @()
    foreach ($line in $rawList) {
      $clean = ($line.ToString() -replace "`0", "").Trim()
      if ($clean -match '^[A-Za-z][A-Za-z0-9._-]*$') { $candidates += $clean }
    }
    if (-not $candidates) {
      Write-Host "[ERROR] wsl -l -q 没列出任何 distro,原始输出:" -ForegroundColor Red
      $rawList | ForEach-Object { Write-Host "  > $_" }
      Write-Error "找不到 WSL distro。先安装一个: wsl --install -d Ubuntu"
      exit 1
    }
    $Distro = $candidates | Where-Object { $_ -match '^Ubuntu' } | Select-Object -First 1
    if (-not $Distro) { $Distro = $candidates | Select-Object -First 1 }
    Write-Host "[INFO] 检测到 distro 候选: $($candidates -join ', '); 使用: $Distro"
  } else {
    Write-Host "[INFO] 使用指定 distro: $Distro"
  }

  # === 3) 自动检测 WSL user ================================================
  if (-not $WslUser) {
    $rawUser = & wsl.exe -d $Distro -e whoami 2>&1
    $WslUser = ($rawUser | Out-String).Trim()
  }
  if (-not ($WslUser -match '^[a-z_][a-z0-9_-]*\$?$')) {
    Write-Host "[ERROR] 拿到的 WSL user 不合法: '$WslUser'" -ForegroundColor Red
    Write-Host "         如果上面是中文乱码,说明 wsl.exe 输出了错误信息" -ForegroundColor Red
    Write-Host "         检查: wsl -l -v   或手动 -Distro <name> -WslUser <user>" -ForegroundColor Red
    Write-Error "无法解析 WSL 用户名"
    exit 1
  }
  Write-Host "[INFO] 目标 distro=$Distro user=$WslUser"

  # === 4) 清理 v1 / v2 残留 =================================================
  # 4a) 杀 v1 残留的 'exec sleep infinity' 长跑进程
  #     注意: v3 自己也会跑一个 sleep infinity, 但命令行带 HOLDER_SIG (后面注册任务时 spawn).
  #     这里只杀 v1 风格的、不带 v3 签名的旧实例.
  $v3Sig = "DevEnvUbuntu-vm-holder-sleep-infinity"
  $existingProcs = Get-CimInstance Win32_Process -Filter "Name = 'wsl.exe'" -ErrorAction SilentlyContinue
  foreach ($ep in $existingProcs) {
    if ($ep.CommandLine -and ($ep.CommandLine -match 'exec sleep infinity') -and ($ep.CommandLine -notmatch [Regex]::Escape($v3Sig))) {
      Write-Host "[INFO] 终止 v1 残留保活进程 PID=$($ep.ProcessId)"
      Stop-Process -Id $ep.ProcessId -Force -ErrorAction SilentlyContinue
    }
  }

  # 4b) 准备运行时目录
  $launcherDir = Join-Path $env:LOCALAPPDATA "DevEnvUbuntu"
  if (-not (Test-Path $launcherDir)) {
    New-Item -ItemType Directory -Path $launcherDir -Force | Out-Null
  }

  # 4c) 删 v1 / v2 旧 VBS
  foreach ($oldVbsName in @("wsl-keepalive.vbs", "wsl-heartbeat.vbs")) {
    $oldVbs = Join-Path $launcherDir $oldVbsName
    if (Test-Path $oldVbs) {
      Remove-Item $oldVbs -Force
      Write-Host "[INFO] 删除旧 VBS: $oldVbs"
    }
  }

  # 4d) 卸载 v2 旧任务 (新任务名是 DevEnvUbuntu-WSL-VMHolder, 不会冲突, 但旧任务还会跑旧 VBS 路径)
  foreach ($oldTaskName in @("DevEnvUbuntu-WSL-Keepalive")) {
    if (Get-ScheduledTask -TaskName $oldTaskName -ErrorAction SilentlyContinue) {
      Write-Host "[INFO] 卸载旧任务: $oldTaskName"
      Unregister-ScheduledTask -TaskName $oldTaskName -Confirm:$false -ErrorAction SilentlyContinue
    }
  }

  # 4e) heartbeat.log 保留 - 留作 v2 历史归档, 用户也可手动删 $launcherDir\heartbeat.log

  # === 5) 生成 vm-holder.vbs ==============================================
  # v3: 不再轮询心跳, 改用持续持有 wsl.exe sleep infinity 子进程模式.
  # 见 docs/superpowers/specs/2026-05-11-vm-holder-design.md.
  $vbsPath  = Join-Path $launcherDir "vm-holder.vbs"
  $logPath  = Join-Path $launcherDir "holder.log"
  $probeTmp = Join-Path $launcherDir "probe.tmp"
  # 签名: WMI 用它在 wsl.exe CommandLine 里识别"我们这份"持有进程
  $holderSig = "DevEnvUbuntu-vm-holder-sleep-infinity"
  $signature = "DevEnvUbuntu-vm-holder:${Distro}:${WslUser}"

  # PowerShell 字符串里 ` 是 escape, " 用 "" 转义; 用 here-string 简化
  $vbs = @"
' DevEnvUbuntu v3 vm-holder.vbs
' Auto-generated by setup-keepalive.ps1 - do not edit by hand
Option Explicit

Const DISTRO       = "$Distro"
Const WSL_USER     = "$WslUser"
Const SIGNATURE    = "$signature"
Const HOLDER_SIG   = "$holderSig"
Const LOG_PATH     = "$($logPath  -replace '\\','\\')"
Const PROBE_TMP    = "$($probeTmp -replace '\\','\\')"
Const MAX_LOG_BYTES = 1048576    ' 1 MB rotate threshold
Const LOOP_INTERVAL_MS = 300000  ' 5 min between probes
Const RESPAWN_GRACE_MS = 10000   ' wait 10s after spawning sleep infinity

' --- helper: append a timestamped log line, rotate at 1MB --------------------
Sub LogLine(level, msg)
  Dim fso, f
  Set fso = CreateObject("Scripting.FileSystemObject")
  If fso.FileExists(LOG_PATH) Then
    If fso.GetFile(LOG_PATH).Size > MAX_LOG_BYTES Then
      Dim rotated : rotated = LOG_PATH & ".1"
      If fso.FileExists(rotated) Then fso.DeleteFile rotated, True
      fso.MoveFile LOG_PATH, rotated
    End If
  End If
  Set f = fso.OpenTextFile(LOG_PATH, 8, True)
  Dim ts : ts = FormatDateTime(Now, 0)
  f.WriteLine ts & " [" & level & "] " & msg
  f.Close
End Sub

' --- helper: query WMI for live wsl.exe with our signature in CommandLine ----
Function IsHolderAlive()
  Dim wmi, procs, p
  IsHolderAlive = False
  On Error Resume Next
  Set wmi = GetObject("winmgmts:\\.\root\cimv2")
  If Err.Number <> 0 Then Exit Function
  Set procs = wmi.ExecQuery( _
    "SELECT ProcessId, CommandLine FROM Win32_Process WHERE Name = 'wsl.exe'")
  For Each p In procs
    If Not IsNull(p.CommandLine) Then
      If InStr(p.CommandLine, HOLDER_SIG) > 0 Then
        IsHolderAlive = True
        Exit Function
      End If
    End If
  Next
  On Error GoTo 0
End Function

' --- helper: read probe.tmp into a string, delete file, strip CR/LF ---------
Function ReadAndDeleteProbeTemp()
  Dim fso, f, s
  Set fso = CreateObject("Scripting.FileSystemObject")
  ReadAndDeleteProbeTemp = ""
  If fso.FileExists(PROBE_TMP) Then
    Set f = fso.OpenTextFile(PROBE_TMP, 1)
    If Not f.AtEndOfStream Then s = f.ReadAll() Else s = ""
    f.Close
    fso.DeleteFile PROBE_TMP, True
    s = Replace(s, vbCrLf, "")
    s = Replace(s, vbLf,   "")
    s = Replace(s, vbCr,   "")
    ReadAndDeleteProbeTemp = Trim(s)
  End If
End Function

' --- helper: get our own wscript.exe PID via WMI (VBScript has no WScript.PID) ---
Function GetSelfPid()
  Dim wmi2, procs2, p2
  GetSelfPid = 0
  On Error Resume Next
  Set wmi2 = GetObject("winmgmts:\\.\root\cimv2")
  If Err.Number <> 0 Then Exit Function
  Set procs2 = wmi2.ExecQuery( _
    "SELECT ProcessId, CommandLine FROM Win32_Process WHERE Name = 'wscript.exe'")
  For Each p2 In procs2
    If Not IsNull(p2.CommandLine) Then
      If InStr(p2.CommandLine, "vm-holder.vbs") > 0 Then
        GetSelfPid = p2.ProcessId
        Exit Function
      End If
    End If
  Next
  On Error GoTo 0
End Function

' --- (a) wscript exclusion: refuse to run if another vm-holder.vbs is up ----
Dim wmi, procs, p, dupCount
On Error Resume Next
Set wmi = GetObject("winmgmts:\\.\root\cimv2")
Set procs = wmi.ExecQuery( _
  "SELECT ProcessId, CommandLine FROM Win32_Process WHERE Name = 'wscript.exe'")
dupCount = 0
For Each p In procs
  If Not IsNull(p.CommandLine) Then
    If InStr(p.CommandLine, "vm-holder.vbs") > 0 Then
      dupCount = dupCount + 1
    End If
  End If
Next
On Error GoTo 0
If dupCount > 1 Then
  WScript.Quit 0
End If

LogLine "INFO", "vm-holder started, pid=" & GetSelfPid()

' --- (b) main loop: hold + probe every 5 minutes -----------------------------
Dim sh : Set sh = CreateObject("WScript.Shell")
Dim holdCmd, coreCmd, probeCmd, exitCode, statusOutput

holdCmd = "wsl.exe -d " & DISTRO & " -u " & WSL_USER & _
          " -e /bin/bash -c ""exec /bin/sleep infinity # " & HOLDER_SIG & """"
coreCmd = "wsl.exe -d " & DISTRO & " -u " & WSL_USER & _
          " -e systemctl --user is-active clautel.service"
probeCmd = "cmd.exe /c """ & coreCmd & " > """ & PROBE_TMP & """ 2>&1"""

Do While True
  ' (b1) hold: respawn if dead
  If Not IsHolderAlive() Then
    LogLine "WARN", "holder child not found, respawning"
    sh.Run holdCmd, 0, False   ' 0=vbHide, False=fire-and-forget
    LogLine "INFO", "vm holder attached (sleep infinity spawned)"
    WScript.Sleep RESPAWN_GRACE_MS
  End If

  ' (b2) probe clautel.service
  exitCode = sh.Run(probeCmd, 0, True)
  statusOutput = ReadAndDeleteProbeTemp()

  ' (b3) three-state log
  If exitCode = 0 And statusOutput = "active" Then
    LogLine "OK", "clautel.service active"
  ElseIf statusOutput = "activating" Then
    LogLine "INFO", "clautel.service activating, give it time"
  Else
    LogLine "WARN", "clautel down (status='" & statusOutput & _
                     "', exit=" & exitCode & "), bootstrapping  # " & SIGNATURE
    Dim bootCmd
    bootCmd = "wsl.exe -d " & DISTRO & " -u " & WSL_USER & _
              " -e systemctl --user start clautel.service"
    sh.Run bootCmd, 0, False
    LogLine "INFO", "boot trigger fired"
  End If

  ' (b4) sleep 5 min until next iteration
  WScript.Sleep LOOP_INTERVAL_MS
Loop
"@

  # write the file (ASCII; no BOM; wscript handles it)
  $vbs | Set-Content -Path $vbsPath -Encoding Ascii -Force
  Write-Host "[OK] 已生成: $vbsPath"

  # === 6) 注册任务: 单 trigger, RestartOnFailure 外层兜底 ====================
  $taskName = "DevEnvUbuntu-WSL-VMHolder"
  $wscript  = Join-Path $env:SystemRoot "System32\wscript.exe"

  $action = New-ScheduledTaskAction -Execute $wscript `
    -Argument ('"{0}"' -f $vbsPath)

  $triggerStartup = New-ScheduledTaskTrigger -AtStartup

  # v3 没有 5min 心跳 trigger - VBS 自己永不退出
  $settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -ExecutionTimeLimit ([TimeSpan]::Zero) -Hidden `
    -MultipleInstances IgnoreNew `
    -RestartCount 999 `
    -RestartInterval (New-TimeSpan -Minutes 1)

  $principal = New-ScheduledTaskPrincipal `
    -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType S4U -RunLevel Highest

  Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue
  Register-ScheduledTask -TaskName $taskName `
    -Action $action `
    -Trigger @($triggerStartup) `
    -Settings $settings -Principal $principal | Out-Null
  Write-Host "[OK] 已注册任务计划: $taskName (AtStartup, S4U, RestartOnFailure=999x60s)"

  # === 6b) 自检注册结果 (防止后续被人意外改回 AtLogOn 或丢掉 S4U) ============
  $registered = Get-ScheduledTask -TaskName $taskName
  $bootTrigger = $registered.Triggers | Where-Object {
    $_.CimClass.CimClassName -eq 'MSFT_TaskBootTrigger'
  }
  if (-not $bootTrigger) {
    throw "[ASSERT] 任务注册成功了, 但没找到 AtStartup (MSFT_TaskBootTrigger). 检查 setup-keepalive.ps1 中 trigger 写法."
  }
  if ($registered.Principal.LogonType -ne 'S4U') {
    throw "[ASSERT] 任务 principal LogonType = '$($registered.Principal.LogonType)', 期望 S4U. 检查 New-ScheduledTaskPrincipal 参数."
  }
  if ($registered.Settings.RestartCount -lt 1) {
    throw "[ASSERT] 任务 RestartCount = '$($registered.Settings.RestartCount)', 期望 >=1. 检查 New-ScheduledTaskSettingsSet -RestartCount."
  }
  Write-Host "[OK] 配置断言通过: AtStartup trigger + S4U principal + RestartOnFailure"

  # === 7) 立即触发一次 + 写 WSL 标记 =======================================
  Start-ScheduledTask -TaskName $taskName
  # v3 holder 内部启动序列: LogLine INFO started -> respawn spread spawn -> LogLine OK probe.
  # 总耗时约 5-10 秒(WSL cold start 占大头). 等 10 秒以保证 3 行都落地.
  Start-Sleep -Seconds 10
  & wsl.exe -d $Distro -u $WslUser -e bash -c "mkdir -p ~/.local/state/devenv && touch ~/.local/state/devenv/windows-keepalive-installed"
  Write-Host "[OK] WSL 端已写入标记文件"

  # === 8) 自检 holder.log ==================================================
  if (Test-Path $logPath) {
    $lastLines = Get-Content $logPath -Tail 5 -ErrorAction SilentlyContinue
    Write-Host "[OK] holder.log 末 5 行:"
    foreach ($line in $lastLines) { Write-Host "      $line" }

    $hasStarted  = $lastLines | Where-Object { $_ -match '\[INFO\] vm-holder started' }
    $hasAttached = $lastLines | Where-Object { $_ -match '\[INFO\] vm holder attached' }
    $hasProbe    = $lastLines | Where-Object { $_ -match '\[(OK|INFO)\] clautel\.service' }

    if (-not $hasStarted)  { Write-Host "[WARN] 未看到 vm-holder started 行, 任务可能没起来" -ForegroundColor Yellow }
    if (-not $hasAttached) { Write-Host "[WARN] 未看到 vm holder attached 行, 持有进程可能 spawn 失败" -ForegroundColor Yellow }
    if (-not $hasProbe)    { Write-Host "[WARN] 未看到 clautel.service 探活行, 检查 12-keepalive.sh 是否跑过" -ForegroundColor Yellow }
  } else {
    Write-Host "[WARN] holder.log 还没生成, 10 秒太短 (Windows 启动期 WSL cold start 可能慢). 几分钟后查 $logPath" -ForegroundColor Yellow
  }

  Write-Host ""
  Write-Host "=== 完成 ===" -ForegroundColor Green
  Write-Host "保活机制 (v3):"
  Write-Host "  AtStartup (S4U, 无密码) -> wscript $vbsPath"
  Write-Host "  VBS 持有 wsl.exe sleep infinity (签名 $holderSig)"
  Write-Host "  VBS 每 5 分钟探活 clautel.service 并写 holder.log"
  Write-Host "  外层兜底: 任务计划 RestartCount=999, Interval=60s (Task Scheduler 最小允许值)"
  Write-Host "  日志: $logPath"
  Write-Host ""
  Write-Host "卸载: Unregister-ScheduledTask -TaskName $taskName -Confirm:`$false"
  Write-Host "      Remove-Item '$launcherDir' -Recurse"

} finally {
  [Console]::OutputEncoding = $prevConsoleOut
}
