# 注册任务计划: 登录时启动 wsl 跑 sleep infinity 保活
# 通过 VBS launcher 实现真正隐藏窗口 + WMI 排他性检查
[CmdletBinding()]
param(
  [string]$Distro,        # 不指定则自动检测默认 distro
  [string]$WslUser        # 不指定则在 distro 里跑 whoami 取
)

$ErrorActionPreference = "Stop"

# 校验管理员
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
  Write-Error "请用管理员权限运行(双击 run-as-admin.bat)"
  exit 1
}

# wsl.exe 默认输出 UTF-16 LE,在 PS5.1 里读出来是乱码;让它走 UTF-8
# (Windows 11 22H2+ / WSL 2.0+ 支持; 旧版本忽略此变量)
$env:WSL_UTF8 = "1"
$prevConsoleOut = [Console]::OutputEncoding
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

try {

  # 1) 写 .wslconfig
  $repoRoot = Split-Path -Parent $PSCommandPath
  $src = Join-Path $repoRoot "wslconfig.template"
  $dst = Join-Path $env:USERPROFILE ".wslconfig"
  Copy-Item $src $dst -Force
  Write-Host "[OK] 已写入 $dst"

  # 2) 自动检测 WSL distro 名(用户没显式传 -Distro 时)
  if (-not $Distro) {
    $rawList = & wsl.exe -l -q 2>&1
    $candidates = @()
    foreach ($line in $rawList) {
      $clean = ($line.ToString() -replace "`0", "").Trim()
      # 只接受合法 distro 名: 字母开头, 后面字母/数字/点/横线/下划线
      if ($clean -match '^[A-Za-z][A-Za-z0-9._-]*$') { $candidates += $clean }
    }
    if (-not $candidates) {
      Write-Host "[ERROR] wsl -l -q 没列出任何 distro,原始输出:" -ForegroundColor Red
      $rawList | ForEach-Object { Write-Host "  > $_" }
      Write-Error "找不到 WSL distro。先安装一个: wsl --install -d Ubuntu"
      exit 1
    }
    # 优先选 Ubuntu 系,否则取第一个
    # 注意: PS 管道单个匹配会拆箱成 string,直接 [0] 会拿首字符 (e.g. 'U' for 'Ubuntu-24.04')
    # Select-Object -First 1 既保留 string 整体,又规范返回类型
    $Distro = $candidates | Where-Object { $_ -match '^Ubuntu' } | Select-Object -First 1
    if (-not $Distro) {
      $Distro = $candidates | Select-Object -First 1
    }
    Write-Host "[INFO] 检测到 distro 候选: $($candidates -join ', '); 使用: $Distro"
  } else {
    Write-Host "[INFO] 使用指定 distro: $Distro"
  }

  # 3) 决定 wsl 用户
  if (-not $WslUser) {
    $rawUser = & wsl.exe -d $Distro -e whoami 2>&1
    $WslUser = ($rawUser | Out-String).Trim()
  }
  if (-not ($WslUser -match '^[a-z_][a-z0-9_-]*\$?$')) {
    Write-Host "[ERROR] 拿到的 WSL user 不是合法 unix 用户名: '$WslUser'" -ForegroundColor Red
    Write-Host "         如果上面是中文乱码,说明 wsl.exe 输出了中文错误信息(WSL_E_*)" -ForegroundColor Red
    Write-Host "         检查: wsl -l -v   或者手动指定: -Distro <name> -WslUser <user>" -ForegroundColor Red
    Write-Error "无法解析 WSL 用户名"
    exit 1
  }
  Write-Host "[INFO] 目标 distro=$Distro user=$WslUser"

  # 3.5) 清掉之前可能残留的旧保活进程(可能是早期版本注册的、command line 没有 signature 的)
  $existingProcs = Get-CimInstance Win32_Process -Filter "Name = 'wsl.exe'" -ErrorAction SilentlyContinue
  foreach ($ep in $existingProcs) {
    if ($ep.CommandLine -and ($ep.CommandLine -match 'exec sleep infinity')) {
      Write-Host "[INFO] 发现已存在的保活进程 PID=$($ep.ProcessId),终止以避免重复"
      Stop-Process -Id $ep.ProcessId -Force -ErrorAction SilentlyContinue
    }
  }

  # 4) 生成 VBS launcher: 隐藏窗口 + WMI 排他性检查
  # VBS 写入 %LOCALAPPDATA%\DevEnvUbuntu\,持久化但不污染仓库,跨机器各自生成
  $launcherDir = Join-Path $env:LOCALAPPDATA "DevEnvUbuntu"
  if (-not (Test-Path $launcherDir)) {
    New-Item -ItemType Directory -Path $launcherDir -Force | Out-Null
  }
  $launcherPath = Join-Path $launcherDir "wsl-keepalive.vbs"
  $signature   = "DevEnvUbuntu-keepalive:$Distro:$WslUser"

  # VBS 内容 (ASCII only,避免 wscript 的编码坑;distro/user 在生成时插值,无硬编码)
  $vbs = @"
' DevEnvUbuntu WSL keepalive launcher
' Auto-generated by setup-keepalive.ps1 - do not edit by hand
' Re-running setup-keepalive.ps1 will overwrite this file.
'
' Behavior:
'   1. Check via WMI whether a keepalive is already running for this
'      (distro, user) pair. If yes, exit silently (singleton).
'   2. Otherwise launch wsl.exe with the bash sleep infinity, hidden,
'      no console window, no wait.
Option Explicit

Const SIGNATURE = "$signature"
Const DISTRO    = "$Distro"
Const WSL_USER  = "$WslUser"

Dim cmdLine
cmdLine = "wsl.exe -d " & DISTRO & " -u " & WSL_USER & _
          " --exec /bin/bash -lic ""exec sleep infinity # " & SIGNATURE & """"

' --- Singleton check via WMI -----------------------------------------------
Dim wmi, procs, p, alreadyRunning
alreadyRunning = False
On Error Resume Next
Set wmi = GetObject("winmgmts:\\.\root\cimv2")
If Err.Number = 0 Then
  Set procs = wmi.ExecQuery( _
    "SELECT ProcessId, CommandLine FROM Win32_Process WHERE Name = 'wsl.exe'")
  If Err.Number = 0 Then
    For Each p In procs
      If Not IsNull(p.CommandLine) Then
        If InStr(p.CommandLine, SIGNATURE) > 0 Then
          alreadyRunning = True
          Exit For
        End If
      End If
    Next
  End If
End If
On Error GoTo 0

If alreadyRunning Then
  WScript.Quit 0
End If

' --- Launch wsl.exe hidden -------------------------------------------------
Dim sh : Set sh = CreateObject("WScript.Shell")
' Run cmdLine, vbHide(0), bWaitOnReturn=False
sh.Run cmdLine, 0, False
"@

  # 写文件 (ASCII, 没有 BOM,wscript 也认得)
  $vbs | Set-Content -Path $launcherPath -Encoding Ascii -Force
  Write-Host "[OK] 已生成隐藏 launcher: $launcherPath"

  # 5) 注册任务计划: 登录时跑 wscript 启动 VBS,VBS 隐藏启动 wsl
  $taskName = "DevEnvUbuntu-WSL-Keepalive"

  # wscript.exe 路径用系统自带的 (避免被 PATH 中的同名 .exe 劫持)
  $wscriptExe = Join-Path $env:SystemRoot "System32\wscript.exe"

  $action = New-ScheduledTaskAction -Execute $wscriptExe `
    -Argument ('"{0}"' -f $launcherPath)
  $trigger = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\$env:USERNAME"
  $settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -StartWhenAvailable -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit ([TimeSpan]::Zero) -Hidden `
    -MultipleInstances IgnoreNew
  $principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -RunLevel Highest

  # 已存在则覆盖
  Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue
  Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal | Out-Null
  Write-Host "[OK] 已注册任务计划: $taskName (MultipleInstances=IgnoreNew)"

  # 6) 立即跑一次 (走 wscript -> VBS -> wsl,全程隐藏)
  Start-ScheduledTask -TaskName $taskName
  Start-Sleep -Seconds 3
  Write-Host "[OK] 任务已触发"

  # 7) 在 WSL 里写标记文件,供 99-verify.sh 读取
  & wsl.exe -d $Distro -u $WslUser -e bash -c "mkdir -p ~/.local/state/devenv && touch ~/.local/state/devenv/windows-keepalive-installed"
  Write-Host "[OK] WSL 端已写入标记文件"

  # 8) 自检: 看 wsl.exe 是否真的跑起来了 (signature 匹配)
  $checkProcs = Get-CimInstance Win32_Process -Filter "Name = 'wsl.exe'" -ErrorAction SilentlyContinue
  $running = $false
  foreach ($cp in $checkProcs) {
    if ($cp.CommandLine -and ($cp.CommandLine.IndexOf($signature) -ge 0)) {
      $running = $true
      Write-Host "[OK] 已检测到保活进程 PID=$($cp.ProcessId) (signature 匹配)"
      break
    }
  }
  if (-not $running) {
    Write-Host "[WARN] 还没看到 signature='$signature' 的 wsl.exe 进程" -ForegroundColor Yellow
    Write-Host "        通常等几秒再 'tasklist /FI \"IMAGENAME eq wsl.exe\"' 应该有"
  }

  Write-Host ""
  Write-Host "=== 完成 ===" -ForegroundColor Green
  Write-Host "保活机制:"
  Write-Host "  1. 任务计划 $taskName 在登录时触发 (MultipleInstances=IgnoreNew)"
  Write-Host "  2. wscript -> $launcherPath -> wsl.exe (隐藏窗口)"
  Write-Host "  3. VBS 启动前 WMI 检查 signature='$signature' 已存在则跳过"
  Write-Host ""
  Write-Host "卸载: Unregister-ScheduledTask -TaskName $taskName -Confirm:`$false"
  Write-Host "      Remove-Item '$launcherDir' -Recurse"

} finally {
  [Console]::OutputEncoding = $prevConsoleOut
}
